name: Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Construir a imagem Docker
        run: docker build -t meu-app:latest .

      - name: Rodar o contêiner
        run: docker run -d -p 8080:80 meu-app:latest
